# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json # Updated path

      - name: Install dependencies
        # working-directory: ./dashboard # Removed, assuming project is at repo root
        run: npm install

      - name: Build project
        # working-directory: ./dashboard # Removed
        run: npm run build
        env:
          # NEXT_PUBLIC_BASE_PATH is automatically handled by Next.js if basePath is set in next.config.js
          # NEXT_PUBLIC_BASE_PATH: /dashboard # This might be redundant
          CI: true # Often used by build tools

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out # Updated path, assuming 'out' is at repo root

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4